[package]
name = "py-horned-owl"
version = "0.2.0"
authors = ["Janna Hastings <j.hastings@ucl.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="pyhornedowl"
crate-type=["cdylib"]

[dependencies.pyo3]
version = "0.15.1"
features = ["extension-module"]

[dependencies]
horned-owl = { path = "../horned-owl", version = "0.12.1-alpha.0"}
curie = "0.1.1"
failure = "0.1.2"

[profile.dev]
opt-level=3
