[package]
name = "py-horned-owl"
version = "0.3.0"
authors = ["Janna Hastings <j.hastings@ucl.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="pyhornedowl"
crate-type=["cdylib"]

[dependencies.pyo3]
version = "0.20"
features = ["abi3-py37", "extension-module", "experimental-inspect"]

[dependencies]
horned-owl = { git = "https://github.com/phillord/horned-owl", version = "0.14.0", tag = "v0.14.0"}
curie = "0.1.1"
failure = "0.1.2"
quote = "1.0"
paste = "1.0"
regex="1.10"

[profile.dev]
opt-level=3
