[package]
name = "py-horned-owl-certus"
version = "0.5.0"
authors = ["Certus Group <engineering@certusgroup.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="pyhornedowl"
crate-type=["cdylib"]

[dependencies.pyo3]
version = "0.20"
features = ["abi3-py37", "extension-module", "experimental-inspect"]

[dependencies]
horned-owl = "1.0"
curie = "0.1.1"
failure = "0.1.2"
quote = "1.0"
paste = "1.0"
regex="1.10"

[profile.dev]
opt-level=3
