name: manylinux
on:
  push:
    branches:
        - master
        - build

  pull_request:
    branches:
        - master
        - build
jobs:
  build_manylinux:
    name: manylinux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          architecture: x64
      - name: build x64_64
        uses: messense/maturin-action@v1
        env:
          RUSTFLAGS: -C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt
        with:
          rust-toolchain: nightly
          maturin-version: latest
          command: build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: target/wheels