name: Build
on:
  push:
    branches:
        - master
        - build

  pull_request:
    branches:
        - master
        - build

jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "windows-latest", "ubuntu-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install maturin==0.13.2
      - name: Build
        run: |
          maturin build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: target/wheels
