name: Build
on:
  push:
    branches:
        - main

  pull_request:
    branches:
        - main
  workflow_call:

jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v3
      - run: cat Cargo.toml
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install maturin==0.13.2
      - name: Build
        uses: messense/maturin-action@v1
        env:
          RUSTFLAGS: -C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt
        with:
          rust-toolchain: nightly
          maturin-version: latest
          command: build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: target/wheels
